version: '3.8'
services:
  evolution_go:
    image: evoapicloud/evolution-go:latest
    container_name: evolution-go
    restart: unless-stopped
    ports:
      - "3381:4000"
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.evolution_go.rule=Host(`go-vps-local.td24.com.br`)
      - traefik.http.routers.evolution_go.entrypoints=web
      - traefik.http.services.evolution_go.loadbalancer.server.port=4000
    volumes:
      - evolution_data:/app/dbdata
      - evolution_logs:/app/logs
    networks:
      - default
volumes:
  evolution_data:
    driver: local
  evolution_logs:
    driver: local
networks:
  default:
    name: evolution_crm_default
    external: true
